version: '3.8'
services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production